# -*- coding: utf-8 -*-
"""Tests for MercadoService.gerar_excel_mensal()."""

import io
from unittest.mock import MagicMock

import pytest

from services.business.mercado_service import MercadoService


def _make_compra(id_, mercado, total, data="2026-02-15"):
    return {
        "id": id_,
        "chat_id": "chat-1",
        "mercado": mercado,
        "total": str(total),
        "data_compra": data,
    }


def _make_item(compra_id, produto, preco, categoria="Outros"):
    return {
        "compra_id": compra_id,
        "produto": produto,
        "preco": str(preco),
        "categoria": categoria,
    }


@pytest.fixture
def mercado_svc():
    svc = MercadoService.__new__(MercadoService)
    svc.name = "mercado"
    svc.logger = MagicMock()
    svc._db = MagicMock()
    svc._db.is_initialized.return_value = True
    return svc


def _mock_db_queries(mock_client, compras_data, itens_data):
    """Wire up the Supabase query chain mock."""
    compras_result = MagicMock()
    compras_result.data = compras_data

    itens_result = MagicMock()
    itens_result.data = itens_data

    call_count = {"n": 0}

    def table_side_effect(name):
        chain = MagicMock()
        chain.select.return_value = chain
        chain.eq.return_value = chain
        chain.gte.return_value = chain
        chain.lt.return_value = chain
        chain.in_.return_value = chain
        chain.order.return_value = chain

        if call_count["n"] == 0:
            chain.execute.return_value = compras_result
        else:
            chain.execute.return_value = itens_result
        call_count["n"] += 1
        return chain

    mock_client.table.side_effect = table_side_effect
    return mock_client


@pytest.mark.asyncio
async def test_generates_valid_xlsx(mercado_svc):
    """Generated bytes start with PK (zip signature = valid xlsx)."""
    compras = [_make_compra(1, "Lidl", 25.50)]
    itens = [_make_item(1, "Leite", 1.20, "Laticínios")]

    mock_client = MagicMock()
    _mock_db_queries(mock_client, compras, itens)
    mercado_svc._get_client = MagicMock(return_value=mock_client)

    result = await mercado_svc.gerar_excel_mensal("chat-1", mes=2, ano=2026)

    assert result["sucesso"] is True
    assert result["excel_bytes"][:2] == b"PK"
    assert result["filename"] == "mercado_report_2026_02.xlsx"
    assert "resumo" in result


@pytest.mark.asyncio
async def test_no_purchases_returns_false(mercado_svc):
    """No purchases in month → sucesso: False."""
    mock_client = MagicMock()
    _mock_db_queries(mock_client, [], [])
    mercado_svc._get_client = MagicMock(return_value=mock_client)

    result = await mercado_svc.gerar_excel_mensal("chat-1", mes=2, ano=2026)

    assert result["sucesso"] is False
    assert "mensagem" in result


@pytest.mark.asyncio
async def test_two_stores_creates_comparison_sheet(mercado_svc):
    """With 2+ stores, a Price Compare sheet is created."""
    compras = [
        _make_compra(1, "Lidl", 20.00),
        _make_compra(2, "Continente", 30.00),
    ]
    itens = [
        _make_item(1, "Leite", 1.10, "Laticínios"),
        _make_item(2, "Leite", 1.30, "Laticínios"),
    ]

    mock_client = MagicMock()
    _mock_db_queries(mock_client, compras, itens)
    mercado_svc._get_client = MagicMock(return_value=mock_client)

    result = await mercado_svc.gerar_excel_mensal("chat-1", mes=2, ano=2026, lang="en")

    assert result["sucesso"] is True

    import openpyxl

    wb = openpyxl.load_workbook(io.BytesIO(result["excel_bytes"]))
    sheet_names = wb.sheetnames
    assert "Price Compare" in sheet_names
    assert len(sheet_names) == 3


@pytest.mark.asyncio
async def test_one_store_no_comparison_sheet(mercado_svc):
    """With only 1 store, no Price Compare sheet."""
    compras = [_make_compra(1, "Lidl", 25.00)]
    itens = [_make_item(1, "Pão", 0.80, "Padaria")]

    mock_client = MagicMock()
    _mock_db_queries(mock_client, compras, itens)
    mercado_svc._get_client = MagicMock(return_value=mock_client)

    result = await mercado_svc.gerar_excel_mensal("chat-1", mes=2, ano=2026, lang="en")

    assert result["sucesso"] is True

    import openpyxl

    wb = openpyxl.load_workbook(io.BytesIO(result["excel_bytes"]))
    assert "Price Compare" not in wb.sheetnames
    assert len(wb.sheetnames) == 2


@pytest.mark.asyncio
async def test_headers_in_english(mercado_svc):
    """Headers are in English when lang='en'."""
    compras = [_make_compra(1, "Tesco", 15.00)]
    itens = [_make_item(1, "Bread", 1.00)]

    mock_client = MagicMock()
    _mock_db_queries(mock_client, compras, itens)
    mercado_svc._get_client = MagicMock(return_value=mock_client)

    result = await mercado_svc.gerar_excel_mensal("chat-1", mes=2, ano=2026, lang="en")

    import openpyxl

    wb = openpyxl.load_workbook(io.BytesIO(result["excel_bytes"]))
    assert wb.sheetnames[0] == "Summary"
    assert wb.sheetnames[1] == "Items"


@pytest.mark.asyncio
async def test_headers_in_portuguese(mercado_svc):
    """Headers are in Portuguese when lang='pt'."""
    compras = [_make_compra(1, "Continente", 18.00)]
    itens = [_make_item(1, "Arroz", 1.50)]

    mock_client = MagicMock()
    _mock_db_queries(mock_client, compras, itens)
    mercado_svc._get_client = MagicMock(return_value=mock_client)

    result = await mercado_svc.gerar_excel_mensal("chat-1", mes=2, ano=2026, lang="pt")

    import openpyxl

    wb = openpyxl.load_workbook(io.BytesIO(result["excel_bytes"]))
    assert wb.sheetnames[0] == "Resumo"
    assert wb.sheetnames[1] == "Itens"
